### ISSUE TITLE
[Questions] fully dynamic routes, utility css, polling, etc

### ISSUE THREAD

**Issue by ITwrx** [al6x/nim#6]
I'm liking a lot about mono, but there are some things i'm not clear on. 

1) fully dynamic routes: i'm evaluating mono to use for a server-rendered application with a cms/admin area. The admin area would allow the user to create the site sections, pages, and content for those pages. The blog example shows dynamic slugs, but does not show how to handle the use case where the previous url segments are also dynamic. Any example/info on this is appreciated.

2) the examples show css classes in css syntax like `li.active`. I'm not seeing any example with multiple utility classes. I plan to use tailwindcss.

3) Why is the front end sending repeated post requests to the server like polling? I've never used websockets or phoenix live view and assumed it wouldn't need to do that.

4) Maybe the github Discussions feature might keep questions and discussions out of the issue tracker?

5) project stability/release strategy? Just wondering how you plan to handle stability, versioning/releases, LTS/backwards compat, etc. 

6) last but not least; asynchttpserver uses ram for (large) file uploads. Any chance mono can support [microasynchttpserver](https://github.com/philip-wernersbach/microasynchttpserver) which evidently allows you to handle the uploaded file differently and is said to have superior performance as well? Bonus points for an example on how to do large file uploads with microasynchttpserver, as idk how yet. :)

thanks!

**Comment by al6x** [comment]
Hey, sorry for delay, haven't noticed your question.

> fully dynamic routes: i'm evaluating mono to use for a server-rendered application with a cms/admin area. The admin area would allow the user to create the site sections, pages, and content for those pages. The blog example shows dynamic slugs, but does not show how to handle the use case where the previous url segments are also dynamic. Any example/info on this is appreciated.

The mono doesn't make any assumption on how you handle your routes. There's the `proc on_location*(self: YourTopLevelComponent, url: Url)` that's called on location change. And it's up to you what to do with the URL, to parse or handle it or just ignore. It doesn't had to be static, dynamic also posisble. Another [example](https://github.com/al6x/nim/blob/dev/keep/ui/location.nim), you can use any location object or even just store it as JSON or even just store the url and then parse the location in `render` proc.

> the examples show css classes in css syntax like li.active. I'm not seeing any example with multiple utility classes. I plan to use tailwindcss.

I'm using tailwind too, you may check [the Palette](https://github.com/al6x/nim/blob/dev/keep/ui/palette.nim) for more examples. You can use `li.active`, `li.a.b.c`, `li .a .b .c`, `el(".a", it.class("more classes"))`.

> Why is the front end sending repeated post requests to the server like polling? I've never used websockets or phoenix live view and assumed it wouldn't need to do that.

Ideally, it should be implemented with websockets. The problem is that Nim server is unstable. So I used only simple HTTP stuff and single-threaded async server, doing old LongPool update. Also, Nim compilation is slow, so I tried to avoid having any extra dependency lie WebSockets. But you are right, LongPool timeouts could be increased to avoid too frequent pinging.

The good thing is that networking in mono implemented as pluggable adapter, so the default simple LongPool networking could be replaced with something else, and default async single-thread mode could be replaced with proper multicore server. You may need to take closer look at networking and maybe tune it for your use case.

> Maybe the github Discussions feature might keep questions and discussions out of the issue tracker?

I think issues are fine for now, I'll create discussion if there will be more questions.

> project stability/release strategy? Just wondering how you plan to handle stability, versioning/releases, LTS/backwards compat, etc.

I'm using mono for my "keep" (a personal notebook, search engine) app. My primary goal is that app, mono is a by-product. I hope I'll publish it in a couple of weeks, so it could be used as Mono example.

The good side is that Mono used for a practical thing and constantly tested, improved and kept real, the bad thing is that I'm not going to invest too much time into docs, etc. Using mono would require to know a bit about how it works, it's a sharp, small tool, that expect that you know how to use it, you going to need to take look at its sources sometimes. As for the releases, I just make changes and bump the version, and try to fix bugs if there's any. Backward compatibility is not a priority, Mono core is like 600 lines of Nim, and I would try to keep it that simple or even simplify further, backward compatibility would overcomplicate it and slow down the progress. Also, unlike say Ruby on Rails, nim type safety makes it easy and safe to update project after incompatible changes.

> last but not least; asynchttpserver uses ram for (large) file uploads. Any chance mono can support [microasynchttpserver](https://github.com/philip-wernersbach/microasynchttpserver) which evidently allows you to handle the uploaded file differently and is said to have superior performance as well? Bonus points for an example on how to do large file uploads with microasynchttpserver, as idk how yet. :)

About the networking, mono is just one function, you take that function and put into some environment, connecting it to networking etc. The default environment is very simple and naive HTTP server (it needs to be rewritten to tolerate serious load). Mono itself doesn't upload files, to use another server like microasynchttpserver, with web-sockets, and efficient data streaming. you need to implement that networking code and connect it to Mono.

Maybe I need to refactor http part of mono into separate `/mono_http` to clearly state that `/mono_http` part is interchangeable, and could be customised with different settings, uploads, networking protocols, auth etc.

About HTTP - In my opinion making robust, high performant, multicore with efficient IO server in Nim, currently is too hard. I think the more practical way to use Nim for production, is same as ruby/python/php single threaded scripts, start N processes, and put it behind load balancer.

**Comment by ITwrx** [comment]
thanks for all of that.

**Comment by al6x** [comment]
You were right about timeouts, it was a bug, I changed it to small values during development and forgot to set back to normal values, thanks for noticing.

As for more advanced http server options, I also forgot that I already refactored the HTTP stuff into [separate HTTP adapter](https://github.com/al6x/nim/tree/main/mono/mono/http) it's ~200 lines of code, it should be easy modify it or create a new one to connect Mono to other servers.
